services:
  client:
    image: "huiying530/fib_calculator_client"
    mem_limit: 128m
    hostname: client

  express:
    image: "huiying530/fib_calculator_server"
    mem_limit: 128m
    hostname: express
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT

  worker:
    image: "huiying530/fib_calculator_worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "huiying530/fib_calculator_nginx"
    mem_limit: 128m
    ports:
      - "3002:80"