services:
  client:
    image: "huiying530/fib_calculator_client"
    mem_limit: 256m
    hostname: client

  express:
    image: "huiying530/fib_calculator_server"
    mem_limit: 512m
    hostname: express
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
  worker:
    image: "huiying530/fib_calculator_worker"
    mem_limit: 256m
    hostname: worker
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
  nginx:
    image: "huiying530/fib_calculator_nginx"
    mem_limit: 256m
    ports:
      - '80:80'
