name: Fib Calculator k8s
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - run: docker build -t huiying530/fib_calculator_kubernetes -f client/Dockerfile.dev client
      - run: docker run -e CI=true huiying530/fib_calculator_kubernetes npm run test


      - run: docker build -t huiying530/fib_calculator_kubernetes_client client
      - run: docker build -t huiying530/fib_calculator_kubernetes_server server
      - run: docker build -t huiying530/fib_calculator_kubernetes_worker worker

      - run: docker push huiying530/fib_calculator_kubernetes_client
      - run: docker push huiying530/fib_calculator_kubernetes_server
      - run: docker push huiying530/fib_calculator_kubernetes_worker